---

# This is temperary solution to get bits from SMP

# Due to the file permission limitation with blob (always 770), we currently only support using azure files.
- name: Install unzip
  apt: 
    name: unzip
    state: latest
    force_apt_get: yes

# Explicitly install bs4 with python3
- name: Install beautifulsoup4
  command: |
    pip3 install beautifulsoup4
  become: true

- name: Download installation media
  shell: "python3 {{ sap_media_download_script_loc }}/python/downloader/basket.py --config /home/{{ ansible_user}}/output.json --dir {{ azure_files_mount_path }}"

- name: Identify media archive
  shell: "ls {{ azure_files_mount_path }}/DB|grep ZIP"
  register: bits_file

- name: Extract media archive
  unarchive: 
    src: "{{ azure_files_mount_path }}/DB/{{bits_file.stdout}}"
    dest: "{{ azure_files_mount_path }}/DB"
    remote_src: yes
    extra_opts:
    - -fo
